#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : APSC 258 Project Report  # The title of the book. Will be placed in the left navbar.
author                      : Julian Joaquin  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : ""  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"
  stderr_output: remove

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex  # The LaTeX engine to use for PDF builds
  #use_jupyterbook_latex: true  # Use the default Jupyter Book LaTeX template
  latex_documents:
    targetname: book.tex

# Configure Sphinx to use the bibtex reference style
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    
# Information about where the book exists on the web
repository:
  url: https://github.com/fellow-sh/apsc_258_project_report  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
